# Generated by Django 2.1.5 on 2019-03-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='prize_worth',
            field=models.CharField(default=1000, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='tournament_poster/'),
        ),
    ]
