# Generated by Django 2.1.5 on 2019-04-04 10:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(default='Anonymous', max_length=100, unique=True, verbose_name='user name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='phone number')),
                ('staff', models.BooleanField(default=False)),
                ('is_club_auth', models.BooleanField(default=False)),
                ('is_governing_body', models.BooleanField(default=False)),
                ('is_player', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_type', models.CharField(choices=[('1', 'Player'), ('2', 'Club'), ('3', 'Governing body'), ('4', 'Admin')], default='1', max_length=2, verbose_name='user type')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_starting_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('number_of_tables', models.PositiveIntegerField(default=1)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('is_valid', models.BooleanField(default=False)),
                ('is_affiliated', models.BooleanField(default=False)),
                ('address', models.TextField()),
                ('latitude', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoverningBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('root_parent', models.CharField(blank=True, default='1', max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Male', max_length=1)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='user/')),
                ('marital_status', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('gameFrequency', models.PositiveIntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('home_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ClubModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuperUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
